<?php
declare(strict_types=1);
require dirname(__DIR__) . '/vendor/autoload.php';
use Coleza\Foundation\Database\Connection;
use Coleza\Domain\Installer\DatabaseSetupService;
use Coleza\Domain\Installer\EmailSetupService;
use Coleza\Domain\Installer\EmailTransportConfig;
use Coleza\Domain\Identity\Rbac\RbacService;
use Coleza\Domain\Commerce\Invoices\InvoiceService;
use Coleza\Domain\Commerce\Orders\OrderService;
use Coleza\Domain\Commerce\Payments\PaymentService;
use Coleza\Domain\Commerce\Payments\Payment;
use Coleza\Domain\Commerce\Payments\Gateways\Iyzico\IyzicoConfiguration;
use Coleza\Domain\Commerce\Payments\Gateways\Iyzico\IyzicoPaymentGateway;
use Coleza\Domain\Commerce\Payments\Gateways\PaymentWebhookHandler;
use Coleza\Application\Commerce\Payments\PaymentApplicationService;
use Coleza\Application\Commerce\Payments\RecordManualPaymentCommand;
function freshDb(): Connection { return new Connection(new PDO('sqlite::memory:', null, null, [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION])); }
function commerce(): array { $db=freshDb(); $o=new OrderService($db);$o->ensureTables();$i=new InvoiceService($db,null,null,$o);$i->ensureTables();$p=new PaymentService($db,$i,$o);$p->ensureTables();return [$db,$i,$p]; }
function probe(string $id, callable $fn): void { try {$r=$fn();echo json_encode(['id'=>$id,'result'=>$r],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).PHP_EOL;}catch(Throwable $e){echo json_encode(['id'=>$id,'exception'=>get_class($e),'message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE).PHP_EOL;} }
probe('R01-installer-rbac',function(){ $db=freshDb();(new DatabaseSetupService())->initializeCoreSchema($db);(new RbacService($db))->hasPermission(1,'invoices.manage');return 'unexpected success'; });
probe('R02-smtp-false-positive',function(){ $config=new EmailTransportConfig(host:'invalid.example',password:'synthetic-only');$r=(new EmailSetupService())->sendTestEmail($config,'nobody@example.com');return ['reported_success'=>$r->isSuccess(),'actual_transport'=>$r->getTransport(),'config_host'=>'invalid.example']; });
probe('R03-smtp-plaintext',function(){ $db=freshDb();(new DatabaseSetupService())->initializeCoreSchema($db);$config=new EmailTransportConfig(host:'invalid.example',password:'synthetic-only');(new EmailSetupService())->configureEmail($db,$config);return $db->selectOne("SELECT setting_value,is_encrypted FROM system_settings WHERE setting_key='mail.password'"); });
probe('R04-client-self-settlement',function(){ [$db,$i,$p]=commerce();$inv=$i->createInvoice(['user_id'=>7,'currency_code'=>'TRY'],[['description'=>'synthetic','unit_amount_minor'=>10000]]);$app=new PaymentApplicationService($p,$i);$pay=$app->recordManualPayment(new RecordManualPaymentCommand(7,(int)$inv->getId(),10000,'TRY','manual'),7,false);return ['payment_status'=>$pay->getStatus(),'invoice_status'=>$i->findInvoiceById((int)$inv->getId())->getStatus()]; });
probe('R05-callback-amount-currency',function(){ [$db,$i,$p]=commerce();$inv=$i->createInvoice(['user_id'=>7,'currency_code'=>'TRY'],[['description'=>'synthetic','unit_amount_minor'=>10000]]);$pay=$p->recordPayment(['user_id'=>7,'invoice_id'=>$inv->getId(),'amount_minor'=>10000,'currency_code'=>'TRY','payment_method'=>'iyzico','status'=>Payment::STATUS_PENDING]);$gateway=new IyzicoPaymentGateway(new IyzicoConfiguration('synthetic-key','synthetic-secret'),fn()=>['body'=>json_encode(['status'=>'success','paymentStatus'=>'SUCCESS','paidPrice'=>'0.01','currency'=>'USD','conversationId'=>$pay->getPaymentNumber(),'paymentId'=>'synthetic','itemTransactions'=>[['paymentTransactionId'=>'synthetic-tx']]])]);$handler=new PaymentWebhookHandler($db,$p,$i);$handler->handleIyzicoCallback($gateway,['token'=>'synthetic-token']);return ['verified_amount_minor'=>1,'verified_currency'=>'USD','expected_amount_minor'=>10000,'expected_currency'=>'TRY','invoice_status'=>$i->findInvoiceById((int)$inv->getId())->getStatus(),'paid_minor'=>$i->findInvoiceById((int)$inv->getId())->getPaidAmountMinor()]; });
probe('R06-emergency-pause-restart',function(){ $a=new Coleza\Domain\Automation\Safety\EmergencyPauseManager();$a->pause('synthetic-admin','audit');$b=new Coleza\Domain\Automation\Safety\EmergencyPauseManager();return ['first_request_paused'=>$a->isPaused(),'next_request_paused'=>$b->isPaused()]; });
probe('R07-remote-backup-loss',function(){ $work=__DIR__.'/probe-data';if(!is_dir($work))mkdir($work);$db=freshDb();$db->statement('CREATE TABLE synthetic_records (id INT)');$db->statement('INSERT INTO synthetic_records VALUES (1)');$dest=new Coleza\Domain\Backup\Storage\S3BackupStorageAdapter([],false);$b=new Coleza\Domain\Backup\EnterpriseBackupService($work,$db);$r=$b->createBackup(Coleza\Domain\Backup\BackupScope::DATABASE,$dest);$id=$r['manifest']->getBackupId();return ['reported_destination'=>$r['destination_type'],'remote_exists'=>$dest->exists($id),'local_archive_exists'=>file_exists($work.'/'.$id.'.zip'),'local_manifest_exists'=>file_exists($work.'/'.$id.'.manifest.json')]; });
probe('R08-invoice-negative-values',function(){ [$db,$i,$p]=commerce();$inv=$i->createInvoice(['user_id'=>7,'currency_code'=>'TRY'],[['description'=>'synthetic','unit_amount_minor'=>-10000]]);return ['total_minor'=>$inv->getTotalMinor(),'status'=>$inv->getStatus()]; });
probe('R09-invoice-overpayment',function(){ [$db,$i,$p]=commerce();$inv=$i->createInvoice(['user_id'=>7,'currency_code'=>'TRY'],[['description'=>'synthetic','unit_amount_minor'=>10000]]);$r=$i->applyPayment((int)$inv->getId(),20000);return ['total_minor'=>$r->getTotalMinor(),'paid_minor'=>$r->getPaidAmountMinor(),'valid_allocations'=>0]; });
probe('R10-fixed-vault-key',function(){ $a=new Coleza\Foundation\Container\Container();(new Coleza\Foundation\Bootstrap\CoreServiceProvider())->register($a);$vault=$a->get(Coleza\Domain\Vault\Encryptor::class);$known=new Coleza\Domain\Vault\Encryptor('base64:'.base64_encode(str_repeat('c',32)));$cipher=$vault->encrypt('synthetic-secret');return ['decrypted_with_public_fallback'=>$known->decrypt($cipher)]; });
probe('R11-backup-apostrophe-restore',function(){ $work=__DIR__.'/probe-data/quote';$db=freshDb();$db->statement('CREATE TABLE synthetic_records (id INT, name TEXT)');$db->statement('INSERT INTO synthetic_records VALUES (?,?)',[1,"O'Reilly"]);$dest=new Coleza\Domain\Backup\Storage\LocalBackupStorageAdapter($work.'/local');$b=new Coleza\Domain\Backup\EnterpriseBackupService($work.'/work',$db);$r=$b->createBackup(Coleza\Domain\Backup\BackupScope::DATABASE,$dest);$restorer=new Coleza\Domain\Backup\RestoreWizardService($work.'/restore');$restored=$restorer->executeRestore($r['manifest']->getBackupId(),$dest,freshDb(),$work.'/target');return $restored->toArray(); });
probe('R12-analytics-commerce-schema',function(){ [$db,$i,$p]=commerce();$inv=$i->createInvoice(['user_id'=>7,'currency_code'=>'TRY'],[['description'=>'synthetic','unit_amount_minor'=>10000]]);$r=(new Coleza\Domain\Analytics\Financial\FinancialMetricsService($db))->calculatePeriodFinancialMetrics('2026-01-01','2027-12-31','TRY');return ['real_invoices'=>1,'real_invoiced_minor'=>10000,'reported_invoice_count'=>$r->getInvoiceCount(),'reported_gross_invoiced'=>$r->getGrossInvoiced()]; });
probe('R13-update-counts-without-running',function(){ $work=__DIR__.'/probe-data/update';if(!is_dir($work.'/files'))mkdir($work.'/files',0755,true);if(!is_dir($work.'/target'))mkdir($work.'/target',0755,true);$db=freshDb();$kp=Coleza\Domain\Updater\PackageSignatureVerifier::generateKeyPair();$manifest=new Coleza\Domain\Updater\UpdatePackageManifest('1.0.1','1.0.0','synthetic',[],[],['CREATE TABLE synthetic_migration (id INT)']);$json=json_encode($manifest->toArray());file_put_contents($work.'/manifest.json',$json);file_put_contents($work.'/manifest.sig',Coleza\Domain\Updater\PackageSignatureVerifier::signPayload($json,$kp['private']));$up=new Coleza\Domain\Updater\StagedUpdateService(new Coleza\Domain\Updater\PackageSignatureVerifier($kp['public']),new Coleza\Domain\Updater\ModuleCompatibilityChecker($db),'1.0.0',$db);$r=$up->applyValidatedUpdate($work,$work.'/target',false);return ['update_result'=>$r,'migration_table_exists'=>$db->selectOne("SELECT name FROM sqlite_master WHERE name='synthetic_migration'")!==null]; });
probe('R14-invoice-list-nplusone',function(){ [$db,$i,$p]=commerce();for($n=0;$n<100;$n++)$i->createInvoice(['user_id'=>7,'currency_code'=>'TRY'],[['description'=>'synthetic','unit_amount_minor'=>100]]);$db->enableQueryLog();$db->flushQueryLog();$result=$i->listInvoicesForUser(7);return ['rows'=>count($result),'queries'=>$db->getQueryCount()]; });
probe('R15-pdf-truncates-long-document',function(){ $html='';for($n=1;$n<=100;$n++)$html.='<p>LINE-'.$n.'</p>';$pdf=(new Coleza\Domain\Documents\Rendering\PurePhpPdfRenderer())->render($html);return ['input_lines'=>100,'contains_last_line'=>str_contains($pdf,'LINE-100'),'single_page'=>str_contains($pdf,'/Count 1')]; });
probe('R16-erasure-keeps-login-password',function(){ $db=freshDb();(new DatabaseSetupService())->initializeCoreSchema($db);$hasher=new Coleza\Domain\Identity\Security\PasswordHasher();$sessions=new Coleza\Domain\Identity\Session\DatabaseSessionHandler($db);$sessions->ensureTable();$auth=new Coleza\Domain\Identity\Auth\AuthService($db,$hasher,$sessions);$uid=$auth->register('synthetic@example.com','SyntheticPassword123!','Synthetic Person');(new Coleza\Domain\Privacy\Erasure\PrivacyErasureService($db))->executeErasure($uid,99,'audit');$row=$db->selectOne('SELECT email,status,is_active,password_hash FROM users WHERE id=?',[$uid]);$login=$auth->authenticate($row['email'],'SyntheticPassword123!');return ['erasure_status'=>$row['status'],'is_active'=>$row['is_active'],'old_password_still_authenticates'=>(int)$login['id']===$uid]; });
probe('R17-export-misses-real-invoice',function(){ [$db,$i,$p]=commerce();$i->createInvoice(['user_id'=>7,'currency_code'=>'TRY'],[['description'=>'synthetic','unit_amount_minor'=>10000]]);$r=(new Coleza\Domain\Privacy\Export\DefaultPrivacyDataCollector($db))->collectUserData(7);return ['real_invoices'=>1,'exported_invoices'=>count($r['invoices'])]; });
probe('R18-health-ignores-real-failed-queue',function(){ $db=freshDb();(new Coleza\Foundation\Queue\DatabaseQueue($db))->ensureTables();for($n=0;$n<20;$n++)$db->statement('INSERT INTO failed_jobs (queue,payload,exception) VALUES (?,?,?)',['synthetic','synthetic','synthetic']);return ['real_failed_jobs'=>20,'reported_health'=>(new Coleza\Domain\Health\SystemDoctorService($db))->checkQueue()->toArray()]; });
probe('R19-paid-invoice-renews-twice',function(){ [$db,$i,$p]=commerce();$ss=new Coleza\Domain\Commerce\Services\ServiceService($db);$ss->ensureTables();$service=$ss->createService(['user_id'=>7,'product_id'=>1,'status'=>'active','billing_cycle'=>'monthly','recurring_amount_minor'=>10000,'currency_code'=>'TRY','next_due_date'=>'2026-11-01','domain'=>'synthetic.example']);$inv=$i->createInvoice(['user_id'=>7,'currency_code'=>'TRY'],[['description'=>'synthetic renewal','unit_amount_minor'=>10000,'service_id'=>$service->getId()]]);$p->recordPayment(['user_id'=>7,'invoice_id'=>$inv->getId(),'amount_minor'=>10000,'currency_code'=>'TRY','payment_method'=>'manual']);$wf=new Coleza\Domain\Commerce\Services\Lifecycle\OverdueLifecycleWorkflow($ss,$i);$wf->handleInvoicePaid((int)$inv->getId());$first=$ss->findServiceById((int)$service->getId())->getNextDueDate();$wf->handleInvoicePaid((int)$inv->getId());$second=$ss->findServiceById((int)$service->getId())->getNextDueDate();return ['after_first'=>$first,'after_replay_same_invoice'=>$second]; });
probe('R20-cpanel-native-transport-error',function(){ $file=__DIR__.'/probe-data/cpanel-local.json';file_put_contents($file,'{"metadata":{"result":1}}');$url='file:///'.str_replace('\\','/',$file);$r=(new Coleza\Domain\Providers\Cpanel\CpanelCurlTransport())->request('GET',$url);return $r; });
probe('R21-server-secret-plaintext',function(){ $db=freshDb();$ss=new Coleza\Domain\Servers\Services\ServerService($db);$ss->ensureTables();$server=$ss->createServer(['name'=>'synthetic','hostname'=>'synthetic.example','ip_address'=>'192.0.2.1','provider_slug'=>'cpanel','auth_secret'=>'synthetic-secret']);return $db->selectOne('SELECT auth_secret_encrypted FROM servers WHERE id=?',[$server->getId()]); });
probe('R22-client-price-override',function(){ $db=freshDb();$pricing=new Coleza\Domain\Pricing\Services\PricingService($db);$pricing->ensureTables();$pricing->setPricePoint(['target_type'=>'product','target_id'=>1,'currency_code'=>'TRY','cycle'=>'monthly','price_minor'=>10000]);$orders=new OrderService($db,$pricing);$orders->ensureTables();$controller=new Coleza\Api\Controllers\Commerce\OrderApiController(new Coleza\Application\Commerce\Orders\OrderApplicationService($orders));$r=$controller->create(['currency_code'=>'TRY','items'=>[['product_id'=>1,'cycle'=>'monthly','unit_price_minor'=>1]]],['user_id'=>7,'is_admin'=>false]);return ['catalog_price_minor'=>10000,'client_supplied_price_minor'=>1,'accepted_order_total_minor'=>$r['data']['total_minor']]; });
probe('R23-support-noop-success',function(){ $db=freshDb();$deps=new Coleza\Domain\Support\Departments\DepartmentService($db);$deps->ensureTables();$dep=$deps->createDepartment(['name'=>'synthetic']);$ts=new Coleza\Domain\Support\Tickets\TicketService($db,$deps);$ts->ensureTables();$ticket=$ts->createTicket(['user_id'=>7,'department_id'=>$dep->getId(),'subject'=>'synthetic','message'=>'synthetic','service_id'=>12345]);$ctx=new Coleza\Domain\Support\Context\TicketContextService($db,$ts,new Coleza\Domain\Support\Context\InMemoryTicketContextProvider());$ctx->ensureTables();$r=$ctx->executeCommand((int)$ticket->getId(),999,'service.reboot');return ['result'=>$r,'real_provider_called'=>false,'registered_handlers'=>0]; });

